name: Clone Website
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out repo
        uses: actions/checkout@v3

      - name: Get repository description
        id: description
        run: |
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}
          DESCRIPTION=$(curl -s "https://api.github.com/repos/$OWNER/$REPO" | jq -r '.description')
          echo "::set-output name=description::$DESCRIPTION"

      - name: Cloning and replacing
        run: |
          git clone https://github.com/aadhitemp/testscript.git out
          rm -rf out/.git
          chmod +x ./out/test.sh
          ./out/test.sh "${{ steps.description.outputs.description }}"

      - name: Push Build
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main # The branch name where you want to push the assets
          FOLDER: out # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: {msg}" # The commit message
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # The private key used to push to the repo
